#
# File::      Rakefile
# Author::    wkm
# Copyright:: 2009
# License::   GPL
#
# Contains tasks for building gems and running tests.
#


require 'rubygems'
require 'rake/clean'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  s.name       = 'sitefuel'
  s.version    = '0.1.0'
  s.author     = 'wkm'
  s.email      = 'wkm@sitefuel.org'
  s.homepage   = 'http://sitefuel.org'
  s.platform   = Gem::Platform::RUBY
  s.summary    = 'A lightweight framework for processing, optimizing, and deploying websites'
  s.bindir     = 'bin'
  s.executables = ['sitefuel']
  s.default_executable = 'sitefuel'
  s.files      = FileList["{bin,test,lib,docs}/**/*"].exclude("rdoc", "pxm", "sh").to_a
  s.require_path     = 'lib'
  s.test_file        = 'test/ts_gem.rb'
  s.has_rdoc         = true
  s.extra_rdoc_files = ['README', 'RELEASE_NOTES']

  s.description = File.read('RELEASE_NOTES')


  s.add_dependency('hpricot', '>= 0.8')
  s.add_dependency('jsmin',   '>= 1.0')
  s.add_dependency('cssmin',  '>= 1.0')
  s.add_dependency('haml',    '>= 2.2')
  

  s.post_install_message = <<END
======================================================
 Thank you for installing SiteFuel 0.1.0.

 Please use caution when using this version of
 SiteFuel to deploy your websites. This should be
 considered an alpha release of SiteFuel and there
 may be bugs which will destroy your code.

 To get started see http://sitefuel.org/getstarted

 SiteFuel comes as an executable program:

  $ sitefuel --help
  $ sitefuel stage website_source
  $ sitefuel deploy website_source webserver_directory

 And also as a Ruby library:

  require 'rubygems'
  require 'sitefuel'

  runtime = SiteFuel::SiteFuelRuntime.new
  # ...

=======================================================
END
  
  # Gem dependencies
  
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
end

# get rid of temporary files generated by processor unit tests
CLEAN.include('**/tmp-*')

# when clobbering destroy any gems that were built
CLOBBER.include('pkg/*')


task :install do
  exec 'sudo gem install pkg/*.gem'
end

task :uninstall do
  exec 'sudo gem uninstall sitefuel'
end

task :reinstall => [:uninstall, :gem, :install]